# Generated by Django 2.1.7 on 2019-05-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/activate', verbose_name='活动室图片')),
                ('title', models.CharField(max_length=256, verbose_name='活动室名称')),
                ('description', models.TextField(verbose_name='活动室描述')),
                ('principal', models.CharField(max_length=32, verbose_name='负责人')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '活动室管理',
                'verbose_name_plural': '活动室管理',
                'db_table': 'activiteroom',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='活动名称')),
                ('location', models.CharField(max_length=255, verbose_name='活动地点')),
                ('introduction', models.TextField(verbose_name='活动介绍')),
                ('principal', models.CharField(max_length=16, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'db_table': 'activate',
            },
        ),
        migrations.CreateModel(
            name='ActivityJion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centent', models.TextField(verbose_name='反馈内容')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Activity', verbose_name='参加活动')),
            ],
            options={
                'verbose_name': '参加活动管理',
                'verbose_name_plural': '参加活动管理',
                'db_table': 'activityjion',
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/baby', verbose_name='照片')),
                ('name', models.CharField(max_length=256, verbose_name='孩子姓名')),
                ('gender', models.BooleanField(choices=[(True, '男'), (False, '女')], default=1, max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '儿童管理',
                'verbose_name_plural': '儿童管理',
                'db_table': 'baby',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('career', models.CharField(max_length=256, verbose_name='职业')),
                ('phone', models.CharField(max_length=16, verbose_name='手机号')),
                ('relation', models.CharField(max_length=64, verbose_name='关系')),
            ],
            options={
                'verbose_name': '扶养人管理',
                'verbose_name_plural': '扶养人管理',
                'db_table': 'dependert',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='建议')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='建议时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Baby', verbose_name='被建议的孩子')),
            ],
            options={
                'verbose_name': '建议管理',
                'verbose_name_plural': '建议管理',
                'db_table': 'suggest',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='用户名')),
                ('hash_password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=256, verbose_name='邮箱')),
                ('status', models.IntegerField(choices=[(1, '未激活'), (2, '激活')], default=1, max_length=2, verbose_name='状态')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='dependent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='baby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='activityjion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.User', verbose_name='用户'),
        ),
    ]
